# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ParsoTest-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ParsoTest-iOS
  pod 'Alamofire', '~> 5.2'
  pod 'NotificationBannerSwift'
  pod 'Kingfisher'

  target 'ParsoTest-iOSTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'ParsoTest-iOSUITests' do
    # Pods for testing

  end

end
